import { CurriculumWeek } from "@/types";

export const CURRICULUM: CurriculumWeek[] = [
  {
    week: 1,
    title: "자기분석 I",
    subtitle: "내 상품은? 서비스는?",
    category: "self-analysis",
    topics: [
      "내 상품/서비스의 핵심 가치 정의",
      "타겟 고객 페르소나 설정",
      "경쟁 상품 대비 차별화 포인트",
      "상품/서비스 스토리 발굴",
    ],
    outcomes: ["상품/서비스 가치 제안서", "타겟 고객 프로필"],
    exercises: 5,
  },
  {
    week: 2,
    title: "자기분석 II",
    subtitle: "나의 강점 & 약점 파악",
    category: "self-analysis",
    topics: [
      "SWOT 분석: 강점, 약점, 기회, 위협",
      "핵심 역량 인벤토리 작성",
      "약점을 강점으로 전환하는 스토리텔링",
      "나만의 유니크 셀링 포인트 도출",
    ],
    outcomes: ["개인 SWOT 분석표", "유니크 포지션 정의"],
    exercises: 5,
  },
  {
    week: 3,
    title: "콘텐츠 제작 I",
    subtitle: "글쓰기 이론",
    category: "content-creation",
    topics: [
      "훅(Hook) 작성법: 스크롤을 멈추게 하는 첫 문장",
      "스토리텔링 구조: 영웅 서사 적용",
      "7코드 콘텐츠 프레임워크 이해",
      "플랫폼별 글쓰기 톤앤매너",
    ],
    outcomes: ["10개 훅 템플릿", "스토리텔링 프레임워크"],
    exercises: 6,
  },
  {
    week: 4,
    title: "콘텐츠 제작 II",
    subtitle: "글쓰기 실습",
    category: "content-creation",
    topics: [
      "인스타그램 캐러셀 콘텐츠 작성",
      "블로그/뉴스레터 롱폼 콘텐츠 작성",
      "CTA(행동 유도) 설계 실습",
      "A/B 테스트용 콘텐츠 변형 작성",
    ],
    outcomes: ["플랫폼별 콘텐츠 3개", "CTA 패턴 5개"],
    exercises: 7,
  },
  {
    week: 5,
    title: "소셜 페르소나 설계 I",
    subtitle: "온라인 정체성 구축",
    category: "persona-design",
    topics: [
      "페르소나 아키타입 선택: 6가지 유형 중 나의 유형",
      "톤앤매너 정의: 말투와 분위기",
      "비주얼 아이덴티티 방향: 색상, 이미지 스타일",
      "바이오/프로필 작성: 첫인상 설계",
    ],
    outcomes: ["페르소나 가이드 문서", "플랫폼별 프로필"],
    exercises: 5,
  },
  {
    week: 6,
    title: "소셜 페르소나 설계 II",
    subtitle: "콘텐츠 전략 실행",
    category: "persona-design",
    topics: [
      "콘텐츠 필러 정의: 3-5개 핵심 주제",
      "콘텐츠 캘린더 설계: 주간/월간 계획",
      "시리즈 기획: 연속성 있는 콘텐츠",
      "첫 콘텐츠 발행 및 피드백",
    ],
    outcomes: ["월간 콘텐츠 캘린더", "첫 콘텐츠 시리즈 발행"],
    exercises: 5,
  },
  {
    week: 7,
    title: "실전 운영 I",
    subtitle: "1일 1콘텐츠 업로드",
    category: "optimization",
    topics: [
      "매일 콘텐츠 발행 루틴 만들기",
      "콘텐츠 배치 작성 및 예약 발행",
      "팔로워 인게이지먼트 전략",
      "댓글/DM 응대 가이드라인",
    ],
    outcomes: ["7일 연속 콘텐츠 발행", "인게이지먼트 분석 리포트"],
    exercises: 7,
  },
  {
    week: 8,
    title: "실전 운영 II",
    subtitle: "SEO & AEO 최적화",
    category: "optimization",
    topics: [
      "SEO 기본 원칙: 검색 최적화 기초",
      "AEO(AI Engine Optimization) 이해: AI 검색 시대 준비",
      "키워드 리서치: 사람들이 찾는 것",
      "메타데이터 최적화: 제목, 설명, 태그",
    ],
    outcomes: ["SEO 체크리스트", "최적화된 콘텐츠 5개"],
    exercises: 6,
  },
];

export const CATEGORY_INFO = {
  "self-analysis": {
    name: "자기분석",
    color: "blue",
    emoji: "🔍",
    description: "나와 내 상품/서비스를 깊이 이해합니다",
  },
  "content-creation": {
    name: "콘텐츠 제작",
    color: "orange",
    emoji: "✍️",
    description: "글쓰기 이론과 실습으로 콘텐츠를 만듭니다",
  },
  "persona-design": {
    name: "페르소나 설계",
    color: "purple",
    emoji: "🎭",
    description: "온라인 정체성을 설계하고 전략을 실행합니다",
  },
  "optimization": {
    name: "실전 운영",
    color: "green",
    emoji: "🚀",
    description: "매일 콘텐츠를 발행하고 최적화합니다",
  },
};

export const CONSULTING_PLANS = [
  {
    id: "total-combat",
    name: "Total Combat",
    price: "50만원",
    duration: "2달 코스",
    description: "소셜 페르소나 설계부터 콘텐츠 발행까지",
    features: [
      "페르소나 분석",
      "소셜 페르소나 설계",
      "콘텐츠 제작 & 발행",
      "온라인 컨설팅 3회",
      "매주 3회 인증 관리",
      "성과 리뷰 미팅 1회",
    ],
  },
  {
    id: "total-scale",
    name: "Total + Scale",
    price: "79만원",
    duration: "4달 풀코스",
    popular: true,
    description: "콘텐츠 시작부터 비즈니스 확장까지 올인원",
    features: [
      "Total Combat 전체 포함",
      "Scale or Die 전체 포함",
      "온라인 컨설팅 총 6회",
      "21만원 할인 혜택",
      "매주 3회 인증 관리",
      "독립 선언 미팅 포함",
    ],
  },
  {
    id: "scale-or-die",
    name: "Scale or Die",
    price: "50만원",
    duration: "2달 코스",
    description: "콘텐츠를 비즈니스로 확장하는 단계",
    features: [
      "콘텐츠 반응 & 성과 분석",
      "비즈니스 모델 리브러싱",
      "메시지 관리 & PR",
      "온라인 컨설팅 3회",
      "매주 3회 인증 관리",
      "독립 선언 미팅 1회",
    ],
  },
];
