import { CurriculumWeek } from "@/types";

export const CURRICULUM: CurriculumWeek[] = [
  {
    week: 1,
    title: "자기분석 I",
    subtitle: "나는 누구인가",
    category: "self-analysis",
    topics: [
      "가치관 탐색: 내가 진정으로 중요하게 여기는 것",
      "강점/약점 분석: 솔직한 자기 평가",
      "과거 경험 회고: 내 이야기의 재료 찾기",
      "롤모델 분석: 닮고 싶은 크리에이터 연구",
    ],
    outcomes: ["나만의 스토리 초안", "핵심 가치 3가지 정의"],
    exercises: 5,
  },
  {
    week: 2,
    title: "자기분석 II",
    subtitle: "나의 전문성 찾기",
    category: "self-analysis",
    topics: [
      "능력 교차점 발견: 2-3가지 능력의 조합",
      "지식/경험 인벤토리: 내가 가진 것들",
      "차별화 포인트 도출: 나만이 할 수 있는 것",
      "약점의 재해석: 약점도 콘텐츠가 된다",
    ],
    outcomes: ["유니크 포지션 정의", "타겟 오디언스 설정"],
    exercises: 5,
  },
  {
    week: 3,
    title: "서비스/제품 분석 I",
    subtitle: "시장 이해하기",
    category: "market-analysis",
    topics: [
      "타겟 시장 분석: 누가 내 콘텐츠를 원할까",
      "경쟁자 분석: 비슷한 크리에이터 연구",
      "트렌드 리서치: 지금 뜨는 주제와 형식",
      "기회 영역 발견: 블루오션 찾기",
    ],
    outcomes: ["시장 포지셔닝 맵", "경쟁 우위 전략"],
    exercises: 4,
  },
  {
    week: 4,
    title: "서비스/제품 분석 II",
    subtitle: "가치 제안 설계",
    category: "market-analysis",
    topics: [
      "USP(고유 판매 제안) 개발: 나만의 강점 정의",
      "가치 제안 캔버스: 고객 니즈와 연결",
      "메시지 프레임워크: 일관된 메시지 구조",
      "엘리베이터 피치: 30초 자기소개",
    ],
    outcomes: ["핵심 메시지 3가지", "엘리베이터 피치"],
    exercises: 4,
  },
  {
    week: 5,
    title: "소셜 페르소나 설계 I",
    subtitle: "온라인 정체성 구축",
    category: "persona-design",
    topics: [
      "페르소나 아키타입 선택: 6가지 유형 중 나의 유형",
      "톤앤매너 정의: 말투와 분위기",
      "비주얼 아이덴티티 방향: 색상, 이미지 스타일",
      "바이오/프로필 작성: 첫인상 설계",
    ],
    outcomes: ["페르소나 가이드 문서", "플랫폼별 프로필"],
    exercises: 5,
  },
  {
    week: 6,
    title: "소셜 페르소나 설계 II",
    subtitle: "콘텐츠 전략 수립",
    category: "persona-design",
    topics: [
      "콘텐츠 필러 정의: 3-5개 핵심 주제",
      "콘텐츠 캘린더 설계: 주간/월간 계획",
      "시리즈 기획: 연속성 있는 콘텐츠",
      "콘텐츠 믹스: 다양한 형식 조합",
    ],
    outcomes: ["월간 콘텐츠 캘린더", "3개 콘텐츠 시리즈 기획"],
    exercises: 5,
  },
  {
    week: 7,
    title: "콘텐츠 제작 I",
    subtitle: "글쓰기 훈련",
    category: "content-creation",
    topics: [
      "훅(Hook) 작성법: 스크롤을 멈추게 하는 첫 문장",
      "스토리텔링 구조: 영웅 서사 적용",
      "메인 아이디어 전개: 핵심을 명확하게",
      "CTA 설계: 행동을 유도하는 마무리",
    ],
    outcomes: ["10개 훅 템플릿", "5개 CTA 패턴"],
    exercises: 7,
  },
  {
    week: 8,
    title: "콘텐츠 제작 II",
    subtitle: "SEO/AEO 최적화",
    category: "content-creation",
    topics: [
      "SEO 기본 원칙: 검색 최적화 기초",
      "AEO(AI Engine Optimization) 이해: AI 검색 시대 준비",
      "키워드 리서치: 사람들이 찾는 것",
      "메타데이터 최적화: 제목, 설명, 태그",
    ],
    outcomes: ["SEO 체크리스트", "최적화된 콘텐츠 5개"],
    exercises: 6,
  },
];

export const CATEGORY_INFO = {
  "self-analysis": {
    name: "자기분석",
    color: "blue",
    emoji: "🔍",
    description: "나를 깊이 이해하고 고유한 강점을 발견합니다",
  },
  "market-analysis": {
    name: "시장분석",
    color: "green",
    emoji: "📊",
    description: "시장을 이해하고 나만의 포지션을 찾습니다",
  },
  "persona-design": {
    name: "페르소나 설계",
    color: "purple",
    emoji: "🎭",
    description: "온라인 정체성을 설계하고 전략을 수립합니다",
  },
  "content-creation": {
    name: "콘텐츠 제작",
    color: "orange",
    emoji: "✍️",
    description: "실제 콘텐츠를 만들고 최적화합니다",
  },
};

export const CONSULTING_PLANS = [
  {
    id: "basic",
    name: "베이직",
    price: "490,000원",
    description: "8주 커리큘럼 + 주 1회 피드백",
    features: [
      "8주 체계적 커리큘럼",
      "주 1회 서면 피드백",
      "전용 워크북 제공",
      "수료 후 1개월 Q&A",
    ],
    duration: "8주",
  },
  {
    id: "standard",
    name: "스탠다드",
    price: "890,000원",
    description: "8주 커리큘럼 + 주 2회 1:1 세션",
    features: [
      "베이직 플랜 전체 포함",
      "주 2회 30분 1:1 화상 세션",
      "실시간 콘텐츠 리뷰",
      "맞춤형 콘텐츠 템플릿",
      "수료 후 3개월 Q&A",
    ],
    duration: "8주",
    popular: true,
  },
  {
    id: "premium",
    name: "프리미엄",
    price: "1,490,000원",
    description: "8주 집중 코칭 + 무제한 피드백",
    features: [
      "스탠다드 플랜 전체 포함",
      "주 3회 45분 1:1 화상 세션",
      "무제한 카카오톡 피드백",
      "콘텐츠 대행 1회",
      "브랜딩 컨설팅 포함",
      "수료 후 6개월 Q&A",
    ],
    duration: "8주",
  },
];
