import { Mission } from "@/types";

export const MISSIONS: Mission[] = [
  // Week 1: 관찰과 기록
  {
    id: "week1-day1",
    week: 1,
    day: 1,
    title: "콘텐츠 관찰자 되기",
    description: "벤치마킹하고 싶은 크리에이터의 콘텐츠를 분석해봐요.",
    task: "벤치마킹하고 싶은 크리에이터 1명의 최근 콘텐츠 3개를 보고, 왜 좋은지 한 줄씩 적어보세요.",
    tips: ["좋아요 수가 아닌 '내가' 왜 좋은지 생각해보세요", "첫인상, 중간, 끝 어떤 부분이 좋은지 구체적으로"],
    estimatedTime: "15분",
  },
  {
    id: "week1-day2",
    week: 1,
    day: 2,
    title: "나의 일상 기록하기",
    description: "콘텐츠의 시작은 일상에서 옵니다.",
    task: "오늘 하루 중 '이거 공유하면 좋겠다' 싶은 순간을 사진 1장으로 남겨보세요.",
    tips: ["완벽할 필요 없어요", "느낌이 오는 순간을 포착하세요"],
    estimatedTime: "10분",
  },
  {
    id: "week1-day3",
    week: 1,
    day: 3,
    title: "한 줄 생각 정리",
    description: "생각을 글로 옮기는 연습을 해봐요.",
    task: "오늘 있었던 일 중 하나를 골라 '배운 점' 한 줄로 정리해보세요.",
    tips: ["교훈적일 필요 없어요", "사소한 것도 괜찮아요"],
    estimatedTime: "10분",
  },
  {
    id: "week1-day4",
    week: 1,
    day: 4,
    title: "트렌드 파악하기",
    description: "지금 사람들이 무엇에 관심 있는지 알아봐요.",
    task: "인스타그램/틱톡 탐색 탭에서 30분간 트렌드를 관찰하고 키워드 3개를 적어보세요.",
    tips: ["스크롤하며 자주 보이는 것", "좋아요가 많은 콘텐츠의 공통점"],
    estimatedTime: "30분",
  },
  {
    id: "week1-day5",
    week: 1,
    day: 5,
    title: "나만의 주제 찾기",
    description: "당신만이 이야기할 수 있는 것은 무엇인가요?",
    task: "내가 자신있게 이야기할 수 있는 주제 5개를 적어보세요.",
    tips: ["직업, 취미, 경험, 관심사 모두 OK", "남들보다 조금이라도 잘 아는 것"],
    estimatedTime: "15분",
  },
  {
    id: "week1-day6",
    week: 1,
    day: 6,
    title: "롤모델 분석",
    description: "벤치마킹할 크리에이터를 정해봐요.",
    task: "나와 비슷한 분야의 크리에이터 3명을 찾고, 각각의 특징을 한 줄로 정리하세요.",
    tips: ["팔로워 수보다 스타일", "내가 되고 싶은 모습과 비슷한 사람"],
    estimatedTime: "20분",
  },
  {
    id: "week1-day7",
    week: 1,
    day: 7,
    title: "1주차 회고",
    description: "한 주를 돌아보며 정리해봐요.",
    task: "이번 주 배운 것 3가지, 다음 주에 해보고 싶은 것 1가지를 적어보세요.",
    tips: ["작은 것도 배움이에요", "솔직하게 적어보세요"],
    estimatedTime: "15분",
  },

  // Week 2: 첫 콘텐츠 만들기
  {
    id: "week2-day1",
    week: 2,
    day: 1,
    title: "콘텐츠 아이디어 브레인스토밍",
    description: "머릿속 아이디어를 꺼내봐요.",
    task: "만들고 싶은 콘텐츠 아이디어 10개를 5분 안에 적어보세요.",
    tips: ["퀄리티 신경 쓰지 마세요", "양이 먼저, 질은 나중에"],
    estimatedTime: "10분",
  },
  {
    id: "week2-day2",
    week: 2,
    day: 2,
    title: "콘텐츠 기획서 작성",
    description: "아이디어를 구체화해봐요.",
    task: "어제 아이디어 중 1개를 골라 간단한 기획서를 작성하세요 (주제, 대상, 핵심 메시지).",
    tips: ["A4 반 장이면 충분해요", "완벽하지 않아도 돼요"],
    estimatedTime: "20분",
  },
  {
    id: "week2-day3",
    week: 2,
    day: 3,
    title: "소재 수집하기",
    description: "콘텐츠에 쓸 재료를 모아봐요.",
    task: "기획한 콘텐츠에 쓸 사진/영상/참고자료를 3개 이상 모아보세요.",
    tips: ["저작권 주의", "나만의 소재가 최고"],
    estimatedTime: "25분",
  },
  {
    id: "week2-day4",
    week: 2,
    day: 4,
    title: "초안 작성",
    description: "일단 만들어봐요, 완벽하지 않아도.",
    task: "기획한 콘텐츠의 초안을 작성하세요 (글, 사진 배치, 영상 순서 등).",
    tips: ["초안은 초안일 뿐", "일단 끝내는 게 중요해요"],
    estimatedTime: "30분",
  },
  {
    id: "week2-day5",
    week: 2,
    day: 5,
    title: "퇴고와 수정",
    description: "다듬으면 빛이 납니다.",
    task: "어제 만든 초안을 3번 읽고 수정할 부분을 체크하세요.",
    tips: ["소리 내어 읽어보세요", "친구에게 보여준다 생각하고"],
    estimatedTime: "20분",
  },
  {
    id: "week2-day6",
    week: 2,
    day: 6,
    title: "첫 콘텐츠 업로드",
    description: "드디어 세상에 공개하는 날!",
    task: "수정한 콘텐츠를 SNS에 업로드하세요.",
    tips: ["떨려도 괜찮아요", "첫 발을 내딛는 것 자체가 성공"],
    estimatedTime: "15분",
  },
  {
    id: "week2-day7",
    week: 2,
    day: 7,
    title: "2주차 회고",
    description: "첫 콘텐츠를 올린 소감을 정리해봐요.",
    task: "업로드 후 느낀 점 3가지, 반응 중 기억에 남는 것 1가지를 적어보세요.",
    tips: ["반응이 없어도 괜찮아요", "올린 것 자체가 대단한 거예요"],
    estimatedTime: "15분",
  },

  // Week 3: 루틴 만들기
  {
    id: "week3-day1",
    week: 3,
    day: 1,
    title: "콘텐츠 루틴 설계",
    description: "꾸준함의 시스템을 만들어봐요.",
    task: "일주일 중 콘텐츠 작업할 요일과 시간을 정하고 캘린더에 표시하세요.",
    tips: ["현실적으로 가능한 시간으로", "작게 시작해도 OK"],
    estimatedTime: "10분",
  },
  {
    id: "week3-day2",
    week: 3,
    day: 2,
    title: "콘텐츠 템플릿 만들기",
    description: "매번 새로 시작하지 마세요.",
    task: "자주 쓸 수 있는 콘텐츠 템플릿(형식)을 1개 만들어보세요.",
    tips: ["반복 사용 가능한 구조로", "수정하기 쉽게"],
    estimatedTime: "25분",
  },
  {
    id: "week3-day3",
    week: 3,
    day: 3,
    title: "영감 수집함 만들기",
    description: "좋은 아이디어를 모아두세요.",
    task: "앞으로 영감을 저장할 공간(폴더, 노트앱 등)을 만들고 3개를 저장하세요.",
    tips: ["접근하기 쉬운 곳에", "분류 기준을 정해두면 좋아요"],
    estimatedTime: "15분",
  },
  {
    id: "week3-day4",
    week: 3,
    day: 4,
    title: "두 번째 콘텐츠 기획",
    description: "이번엔 조금 더 빠르게.",
    task: "새로운 콘텐츠 아이디어를 기획하고 간단히 정리하세요.",
    tips: ["첫 번째 경험을 활용하세요", "너무 어렵게 생각하지 마세요"],
    estimatedTime: "20분",
  },
  {
    id: "week3-day5",
    week: 3,
    day: 5,
    title: "두 번째 콘텐츠 제작",
    description: "속도가 붙기 시작해요.",
    task: "기획한 콘텐츠를 제작하세요.",
    tips: ["완벽보다 완성", "시간을 정해두고 해보세요"],
    estimatedTime: "30분",
  },
  {
    id: "week3-day6",
    week: 3,
    day: 6,
    title: "두 번째 콘텐츠 업로드",
    description: "루틴이 만들어지고 있어요!",
    task: "제작한 콘텐츠를 업로드하세요.",
    tips: ["업로드 시간도 일정하게 해보세요", "해시태그 연구해보기"],
    estimatedTime: "15분",
  },
  {
    id: "week3-day7",
    week: 3,
    day: 7,
    title: "3주차 회고",
    description: "루틴이 잡혀가고 있나요?",
    task: "이번 주 루틴 지킨 정도와 다음 주 개선점을 적어보세요.",
    tips: ["못 지킨 것도 기록", "왜 못 지켰는지 분석"],
    estimatedTime: "15분",
  },

  // Week 4: 피드백과 개선
  {
    id: "week4-day1",
    week: 4,
    day: 1,
    title: "콘텐츠 성과 분석",
    description: "숫자가 말해주는 것들.",
    task: "지금까지 올린 콘텐츠의 조회수, 좋아요, 댓글 수를 기록하세요.",
    tips: ["숫자에 일희일비하지 마세요", "추이를 보는 것이 중요"],
    estimatedTime: "15분",
  },
  {
    id: "week4-day2",
    week: 4,
    day: 2,
    title: "댓글/DM 분석",
    description: "독자의 목소리를 들어봐요.",
    task: "받은 피드백(댓글, DM 등)을 모아보고 공통점을 찾아보세요.",
    tips: ["긍정/부정 모두 귀중해요", "요청사항은 기회입니다"],
    estimatedTime: "20분",
  },
  {
    id: "week4-day3",
    week: 4,
    day: 3,
    title: "경쟁사 비교 분석",
    description: "다른 사람은 어떻게 하고 있을까?",
    task: "비슷한 주제의 크리에이터 3명의 최근 콘텐츠와 내 콘텐츠를 비교 분석하세요.",
    tips: ["배울 점과 차별화 포인트 찾기", "따라하기보다 영감 얻기"],
    estimatedTime: "25분",
  },
  {
    id: "week4-day4",
    week: 4,
    day: 4,
    title: "개선 포인트 도출",
    description: "이제 업그레이드할 시간.",
    task: "분석 결과를 바탕으로 개선할 점 3가지를 구체적으로 적어보세요.",
    tips: ["한 번에 다 고치려 하지 마세요", "가장 중요한 것부터"],
    estimatedTime: "20분",
  },
  {
    id: "week4-day5",
    week: 4,
    day: 5,
    title: "개선된 콘텐츠 기획",
    description: "배운 것을 적용해봐요.",
    task: "개선점을 반영한 새 콘텐츠를 기획하세요.",
    tips: ["너무 많이 바꾸지 마세요", "1-2가지 변화로 시작"],
    estimatedTime: "20분",
  },
  {
    id: "week4-day6",
    week: 4,
    day: 6,
    title: "세 번째 콘텐츠 업로드",
    description: "개선된 버전을 세상에!",
    task: "개선점을 반영한 콘텐츠를 제작하고 업로드하세요.",
    tips: ["변화를 두려워하지 마세요", "실험 정신으로"],
    estimatedTime: "40분",
  },
  {
    id: "week4-day7",
    week: 4,
    day: 7,
    title: "4주차 회고 - 중간 점검",
    description: "절반 왔어요! 대단합니다.",
    task: "4주간의 여정을 돌아보며 성장한 점과 남은 과제를 정리하세요.",
    tips: ["작은 성장도 인정하세요", "남은 4주 계획도 세워봐요"],
    estimatedTime: "20분",
  },

  // Week 5: 스타일 확립
  {
    id: "week5-day1",
    week: 5,
    day: 1,
    title: "나만의 톤앤매너 정의",
    description: "당신만의 색깔을 찾아봐요.",
    task: "내 콘텐츠의 톤앤매너를 3가지 키워드로 정의하세요.",
    tips: ["친구랑 대화하듯? 전문가처럼?", "일관성이 중요해요"],
    estimatedTime: "15분",
  },
  {
    id: "week5-day2",
    week: 5,
    day: 2,
    title: "비주얼 아이덴티티 만들기",
    description: "보이는 것도 중요해요.",
    task: "내 콘텐츠에 사용할 색상, 폰트, 이미지 스타일을 정해보세요.",
    tips: ["일관된 비주얼이 기억에 남아요", "참고 이미지 모아보기"],
    estimatedTime: "25분",
  },
  {
    id: "week5-day3",
    week: 5,
    day: 3,
    title: "시그니처 요소 만들기",
    description: "기억에 남는 포인트.",
    task: "내 콘텐츠만의 특별한 요소(인사말, 마무리 멘트, 특별 코너 등)를 만들어보세요.",
    tips: ["따라하기 쉽고 기억에 남는 것", "진정성 있게"],
    estimatedTime: "20분",
  },
  {
    id: "week5-day4",
    week: 5,
    day: 4,
    title: "콘텐츠 시리즈 기획",
    description: "지속 가능한 콘텐츠를 만들어봐요.",
    task: "정기적으로 올릴 수 있는 시리즈 콘텐츠 아이디어를 기획하세요.",
    tips: ["주 1회 올릴 수 있는 것", "변형하기 쉬운 포맷으로"],
    estimatedTime: "25분",
  },
  {
    id: "week5-day5",
    week: 5,
    day: 5,
    title: "시리즈 첫 번째 콘텐츠",
    description: "새로운 시작!",
    task: "기획한 시리즈의 첫 번째 콘텐츠를 제작하세요.",
    tips: ["시리즈임을 알 수 있게", "다음 편에 대한 기대감 주기"],
    estimatedTime: "35분",
  },
  {
    id: "week5-day6",
    week: 5,
    day: 6,
    title: "네 번째 콘텐츠 업로드",
    description: "시리즈의 시작을 알려요!",
    task: "시리즈 첫 번째 콘텐츠를 업로드하세요.",
    tips: ["시리즈 예고도 함께", "피드백 요청도 좋아요"],
    estimatedTime: "15분",
  },
  {
    id: "week5-day7",
    week: 5,
    day: 7,
    title: "5주차 회고",
    description: "스타일이 잡혀가고 있나요?",
    task: "이번 주 정의한 스타일 요소들을 정리하고 적용 계획을 세우세요.",
    tips: ["모든 콘텐츠에 일관되게", "필요하면 수정해도 OK"],
    estimatedTime: "15분",
  },

  // Week 6: 성장 가속화
  {
    id: "week6-day1",
    week: 6,
    day: 1,
    title: "알고리즘 이해하기",
    description: "플랫폼의 언어를 배워봐요.",
    task: "내가 사용하는 플랫폼의 알고리즘 특성을 조사하고 정리하세요.",
    tips: ["공식 가이드 확인", "최신 정보 찾기"],
    estimatedTime: "25분",
  },
  {
    id: "week6-day2",
    week: 6,
    day: 2,
    title: "해시태그 전략 수립",
    description: "발견되는 콘텐츠가 되어봐요.",
    task: "내 콘텐츠에 사용할 해시태그 리스트(30개)를 만들어보세요.",
    tips: ["대형/중형/소형 해시태그 섞기", "관련성이 최우선"],
    estimatedTime: "30분",
  },
  {
    id: "week6-day3",
    week: 6,
    day: 3,
    title: "업로드 시간 최적화",
    description: "언제 올리느냐도 중요해요.",
    task: "타겟 독자가 가장 활발한 시간대를 분석하고 업로드 시간을 정하세요.",
    tips: ["인사이트 데이터 활용", "테스트해보기"],
    estimatedTime: "20분",
  },
  {
    id: "week6-day4",
    week: 6,
    day: 4,
    title: "협업 기회 탐색",
    description: "함께하면 더 멀리 갈 수 있어요.",
    task: "협업하고 싶은 크리에이터/브랜드 5개를 찾고 협업 아이디어를 적어보세요.",
    tips: ["비슷한 규모끼리", "서로 윈윈이 되는 관계"],
    estimatedTime: "25분",
  },
  {
    id: "week6-day5",
    week: 6,
    day: 5,
    title: "시리즈 두 번째 콘텐츠",
    description: "연속성을 보여줘요.",
    task: "시리즈 두 번째 콘텐츠를 제작하세요.",
    tips: ["첫 번째와 연결 고리", "새로운 분들을 위한 배려도"],
    estimatedTime: "35분",
  },
  {
    id: "week6-day6",
    week: 6,
    day: 6,
    title: "다섯 번째 콘텐츠 업로드",
    description: "배운 전략을 적용해봐요!",
    task: "최적화 전략을 적용해 콘텐츠를 업로드하세요.",
    tips: ["해시태그, 시간 적용", "결과 모니터링"],
    estimatedTime: "15분",
  },
  {
    id: "week6-day7",
    week: 6,
    day: 7,
    title: "6주차 회고",
    description: "성장 전략의 효과는?",
    task: "이번 주 적용한 전략의 효과를 분석하고 다음 주 계획을 세우세요.",
    tips: ["숫자로 비교해보기", "효과 있는 것 계속, 없는 것 수정"],
    estimatedTime: "20분",
  },

  // Week 7: 커뮤니티 형성
  {
    id: "week7-day1",
    week: 7,
    day: 1,
    title: "팔로워와 소통하기",
    description: "관계가 팬을 만들어요.",
    task: "오늘 받은 모든 댓글에 진심을 담아 답글을 달아보세요.",
    tips: ["복붙 금지", "질문으로 대화 이어가기"],
    estimatedTime: "20분",
  },
  {
    id: "week7-day2",
    week: 7,
    day: 2,
    title: "참여형 콘텐츠 만들기",
    description: "함께 만드는 콘텐츠.",
    task: "팔로워가 참여할 수 있는 콘텐츠(질문, 설문, 챌린지 등)를 기획하세요.",
    tips: ["참여 허들 낮게", "참여하면 좋은 이유 제시"],
    estimatedTime: "25분",
  },
  {
    id: "week7-day3",
    week: 7,
    day: 3,
    title: "커뮤니티 가이드라인 만들기",
    description: "건강한 커뮤니티의 기반.",
    task: "내 채널의 분위기와 규칙을 정하고 소개글에 반영하세요.",
    tips: ["긍정적인 톤으로", "명확하게"],
    estimatedTime: "20분",
  },
  {
    id: "week7-day4",
    week: 7,
    day: 4,
    title: "팬 감사 콘텐츠 기획",
    description: "고마움을 표현해봐요.",
    task: "팔로워들에게 감사를 표현하는 콘텐츠를 기획하세요.",
    tips: ["진심이 담긴 메시지", "특별한 혜택도 좋아요"],
    estimatedTime: "20분",
  },
  {
    id: "week7-day5",
    week: 7,
    day: 5,
    title: "시리즈 세 번째 콘텐츠",
    description: "시리즈가 자리잡고 있어요!",
    task: "시리즈 세 번째 콘텐츠를 제작하세요.",
    tips: ["패턴이 익숙해지고 있죠?", "새로운 시도도 조금씩"],
    estimatedTime: "35분",
  },
  {
    id: "week7-day6",
    week: 7,
    day: 6,
    title: "여섯 번째 콘텐츠 업로드",
    description: "커뮤니티와 함께하는 콘텐츠!",
    task: "참여형 또는 감사 콘텐츠를 업로드하세요.",
    tips: ["팔로워 반응 적극 수집", "참여자에게 반응하기"],
    estimatedTime: "15분",
  },
  {
    id: "week7-day7",
    week: 7,
    day: 7,
    title: "7주차 회고",
    description: "커뮤니티가 형성되고 있나요?",
    task: "이번 주 소통 활동과 반응을 정리하고 커뮤니티 성장 계획을 세우세요.",
    tips: ["양보다 질", "진성 팬 몇 명이면 충분"],
    estimatedTime: "20분",
  },

  // Week 8: 마무리와 지속
  {
    id: "week8-day1",
    week: 8,
    day: 1,
    title: "8주 성과 종합 분석",
    description: "당신이 이룬 것들.",
    task: "8주간의 모든 데이터를 정리하고 성장 그래프를 만들어보세요.",
    tips: ["시작과 현재 비교", "숫자 외의 성장도 기록"],
    estimatedTime: "30분",
  },
  {
    id: "week8-day2",
    week: 8,
    day: 2,
    title: "베스트 콘텐츠 분석",
    description: "무엇이 통했는지 알아봐요.",
    task: "가장 성과 좋았던 콘텐츠 3개를 분석하고 성공 요인을 정리하세요.",
    tips: ["공통점 찾기", "재현 가능한 요소 추출"],
    estimatedTime: "25분",
  },
  {
    id: "week8-day3",
    week: 8,
    day: 3,
    title: "실패에서 배우기",
    description: "실패도 자산이에요.",
    task: "기대보다 반응이 적었던 콘텐츠를 분석하고 배운 점을 정리하세요.",
    tips: ["자책 금지", "개선 포인트 도출"],
    estimatedTime: "25분",
  },
  {
    id: "week8-day4",
    week: 8,
    day: 4,
    title: "앞으로의 3개월 계획",
    description: "여기서 끝이 아니에요.",
    task: "다음 3개월의 콘텐츠 목표와 계획을 세우세요.",
    tips: ["구체적이고 측정 가능하게", "무리하지 않게"],
    estimatedTime: "30분",
  },
  {
    id: "week8-day5",
    week: 8,
    day: 5,
    title: "마지막 시리즈 콘텐츠",
    description: "시리즈의 피날레!",
    task: "시리즈 마지막 콘텐츠를 제작하세요.",
    tips: ["지금까지의 여정 담기", "다음 시리즈 예고도"],
    estimatedTime: "35분",
  },
  {
    id: "week8-day6",
    week: 8,
    day: 6,
    title: "일곱 번째 콘텐츠 업로드",
    description: "8주 프로그램의 마무리!",
    task: "마지막 콘텐츠를 업로드하고 팔로워들에게 감사 인사를 전하세요.",
    tips: ["여정 공유", "앞으로의 계획 공유"],
    estimatedTime: "20분",
  },
  {
    id: "week8-day7",
    week: 8,
    day: 7,
    title: "8주 완주 회고",
    description: "축하합니다! 당신은 해냈어요!",
    task: "8주간의 여정을 총정리하고, 미래의 자신에게 편지를 써보세요.",
    tips: ["모든 성장을 인정하세요", "이제 시작일 뿐이에요"],
    estimatedTime: "30분",
  },
];

// 미션 조회 함수
export function getMission(missionId: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === missionId);
}

export function getMissionsByWeek(week: number): Mission[] {
  return MISSIONS.filter((m) => m.week === week);
}

export function getTodayMission(week: number, day: number): Mission | undefined {
  return MISSIONS.find((m) => m.week === week && m.day === day);
}
